version: "3.8"

services:
  mysql-patient:
    container_name: mysql-Patient
    image: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql
  springboot-userService:
    container_name: user-service-container
    image: user-service-image
    build:
      context: ./
      dockerfile: DockerFile
    ports:
      - 8081:8080
    environment:
      MYSQL_HOST: mysql-patient
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: 3306
    depends_on:
      - mysql-patient
    restart: on-failure
volumes:
  mysql-data: